### ISSUE TITLE
Sniff for typed Arrays accesses __proto__.

### ISSUE THREAD

**Issue by kitsonk** [jspm/jspm-core#2]
For security reasons, we have removed `__proto__` in Deno, but the buffer supports attempts to access and augment `__proto__`.  Because of that, some of the JSPM packages which rely on Node buffer support now are broken on Deno.

https://github.com/jspm/jspm-core/blob/47718c6ca94a34f95446c887806207f3c9177a65/nodelibs/buffer.js#L260-L274

What is needed to support JSPM without augmenting the prototypes of globals?

**Comment by guybedford** [comment]
Thanks for catching this and posting, it should ideally be possible for these typed arrays to be new extended prototypes as opposed to modifying the browser builtins, but I haven't looked into the issue that deeply to see why this wasn't the original approach and what that might affect.

The direct issue would be one for buffer here - https://github.com/feross/buffer. So the first step would be to post there and see if Feross is interested in alternative approaches. If not, getting these sorts of issues fixed in jspm is a priority so we can fork here as necessary.

**Comment by kitsonk** [comment]
@guybedford it looks like master of `feross/buffer` has already changed to not access `__proto__`: https://github.com/feross/buffer/blob/b0a6de5f2131c3e339f14801bb342d16d580ac5f/index.js#L49-L60.  It does try to modify the prototype in the sniff, though in functional code, it doesn't actually do this, so I am not sure the sniff is valid and will raise an issue.  We haven't yet frozen built-ins by default, and if we did, it would cause a problem again, but at least we know that it will have some ancillary damage if we do.

So it just seems that if JSPM were to update to a newer version of feross/buffer then at least the access to `__proto__` would stop causing problems.

**Comment by kitsonk** [comment]
Sorry, actually looking at the code again, it doesn't modify the prototype in the sniff, it just tries to copy it, which is what it does in the functional code.  Freezing the built-ins wouldn't break again.

**Comment by guybedford** [comment]
Ok it sounds like just updating Buffer here and releasing a new core build should be enough then?

I will aim to get that out in the next couple of days.

**Comment by kitsonk** [comment]
Yes, it feels that it would.  Awesome, thank you.

**Comment by guybedford** [comment]
I just landed this upgrade in [master](https://github.com/jspm/jspm-core/commit/84cd771baa81779422bfbe61ff73cb5d4d33962d) and on the [2.0 branch](https://github.com/jspm/jspm-core/commit/d95a65ecdc35ca2a65da2f0a1c2771b4b31bda0a).

I've just published the 2.0 upgrade in 2.0.0-beta.4 and am just running the development CDN tests against that before publishing the 1.0 version once its clear package support is all working.

**Comment by guybedford** [comment]
@kitsonk all the smoke tests seem to be behaving correctly so I've published the 1.1.0 of @jspm/core. I'd give it half an hour to ensure it properly refreshes on the CDN.

FWIW, the upcoming 3.0 dev server will prioritize freshness for the dev server, while supporting a new production server rather than this middle ground, but the release is still a little way away yet.

I double checked the new buffer build here doesn't have any `__proto__` tricks and there doesn't seem to be anything like that now.

Will leave this issue open until we've confirmed it resolves the issue though, so please do post back when you try it out.

**Comment by kitsonk** [comment]
@guybedford thank you very much, I have been able to verify that JSPM that require Node.js Buffer work under recent releases of Deno since we have removed `__proto__`.
